Repository HFG43/final_capstone_front_end, pull requests merged in 2023-11, with the labels that each got.

#21 Create the User Slice
  src/Redux/store.js
  src/Redux/users/usersSlice.js
Labels: enhancement

#23 Create Reservations Slice
  src/Redux/Slices/reservationsSlice.js
  src/Redux/store.js
  src/customHooks/useSession.js
Labels: enhancement

#24 Register form
  .gitignore
  src/App.js
  src/Components/LoginPage.jsx
  src/Components/Register.jsx
  src/Redux/Slices/usersSlice.js
  src/Style/Login.css
  src/Style/medias.css
  src/Style/register.css
  src/img/back.webp
Labels: enhancement

#25 Reservation form
  src/Components/Register.jsx
  src/Components/ReservationForm.jsx
  src/Redux/Slices/reservationsSlice.js
  src/Style/medias.css
  src/Style/register.css
  src/customHooks/useSession.js
  src/logic/formatObjects.js
  src/logic/getDate.js
Labels: enhancement

#26 Add assets and fonts
  package-lock.json
  package.json
  src/img/bg.webp
  src/img/login-image.jpg
  src/index.css
Labels: enhancement

#27 Display all the user reservations
  src/App.js
  src/Components/MyReservations.jsx
  src/Components/ReservationCard.jsx
  src/Components/ReservationForm.jsx
  src/Style/medias.css
  src/Style/myReservation.css
  src/Style/register.css
  src/logic/formatObjects.js
  src/logic/getDate.js
Labels: enhancement

#30 Add Experience Details Page
  public/index.html
  src/App.js
  src/Components/ExperienceCard.js
  src/Components/ExperienceDetails.jsx
  src/Components/ExperienceIncluded.jsx
  src/Components/MainPage.jsx
  src/Components/ReservationForm.jsx
  src/Components/RoutesWrapper.js
  src/Redux/Slices/usersSlice.js
  src/Style/experienceDetails.css
  src/Style/medias.css
  src/index.css
  src/logic/utils.js
Labels: documentation, enhancement

#36 Add delete experiences
  src/App.js
  src/Components/AddExperience.jsx
  src/Components/DeleteExperience.jsx
  src/Components/ExperienceDetails.jsx
  src/Components/LoginPage.jsx
  src/Components/MainPage.jsx
  src/Components/MyReservations.jsx
  src/Components/NavBar.jsx
  src/Components/ReservationCard.jsx
  src/Components/RoutesWrapper.js
  src/Redux/Slices/ExperiencesSlice.js
  src/Redux/Slices/usersSlice.js
  src/Style/NavBar.css
  src/Style/myReservation.css
  src/Style/register.css
  src/logic/formatObjects.js
  src/logic/getDate.js
  src/logic/utils.js
Labels: documentation
